### ISSUE TITLE
get mysql db locale and pass it to my graphql helper functions

### ISSUE THREAD

**Issue by vtrofin** [vtrofin/takezo#11]
How do I pass the db locale to a function like this one below ?
https://github.com/vtrofin/takezo/blob/afd59ef31f31ce97af9df04d40d8533aa4adee5e/ql/qlhelpers.js#L26-L44  

In initDb i just console.log the const lcTimeNames since I haven't figured out of a way to access the variable in qlhelpers.
https://github.com/vtrofin/takezo/blob/afd59ef31f31ce97af9df04d40d8533aa4adee5e/initDb.js#L26-L34

**Comment by martinheidegger** [comment]
In `initDb.js` you specified the return value for `initDb()`. This is "just" the database object. so: none of your following code has access to the locale. 

https://github.com/vtrofin/takezo/blob/afd59ef31f31ce97af9df04d40d8533aa4adee5e/initDb.js#L35

If you want other code to have access to some more data then you need to return more data. That being said: This might be the wrong solution here. It is better to store the time always in the same format. Usually a number is sufficient to me but in order to allow for an infinite dataspace string might be better too. You might wonder: "but how about displaying the number": Well when you need to display the time data a library such as [moment](http://momentjs.com/) might come in handy to be used in all interactions from<->to the database.
